# Generated by Django 5.1.2 on 2024-10-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
